In [1]:
import pandas as pd
df_vendas = pd.read_csv('vendas.csv')

In [2]:
df_vendas.head()

,data,produto,categoria,quantidade,preco_unitario,cliente,regiao
0,2025-12-09,Headset G,Periféricos,1,2759,Fernanda,Sudeste
1,2025-03-12,Armário P,Móveis,2,4516,Rafael,Norte
2,2025-11-24,Mesa Escritório N,Móveis,1,4347,Rafael,Sudeste
3,2025-09-14,Tênis T,Vestuário,3,3046,Ana,Norte
4,2025-08-03,Boné V,Vestuário,2,4453,Bruno,Centro-Oeste

In [ ]:
df_vendas.shape[0]  # Número de linhas

100

In [4]:
df_vendas["Receita_Total"] = df_vendas["quantidade"] * df_vendas["preco_unitario"]
display(df_vendas[["produto", "Receita_Total"]])

              produto  Receita_Total
0           Headset G           2759
1           Armário P           9032
2   Mesa Escritório N           4347
3             Tênis T           9138
4              Boné V           8906
..                ...            ...
95       Impressora I          13683
96          Celular A           2046
97          Celular A          21950
98            Calça U          12360
99           Camisa R          15200

[100 rows x 2 columns]

In [5]:
df_vendas.groupby("categoria")[["Receita_Total" ]].sum()

             Receita_Total
categoria
Eletrônicos         239389
Móveis              228789
Periféricos         162285
Vestuário           215389

In [6]:
produto_mais_vendido = df_vendas[["produto", "quantidade"]].groupby("produto").sum().sort_values(by="quantidade", ascending=False).head(1)

produto_mais_vendido

         quantidade
produto
Sofá Q           30

In [7]:
regiao_mais_vendas = df_vendas[["regiao", "quantidade"]].groupby("regiao").sum().sort_values(by="quantidade", ascending=False).head(1)
regiao_mais_vendas

         quantidade
regiao
Sudeste          90